# GRPO Configuration - Ported from RL2/trainer/config/ppo.yaml
# Reference: RL2/trainer/config/ppo.yaml lines 1-104
# Configured for GRPO with adv.norm_var=true, kl.reward_estimator=k3, adv.estimator=reinforce

data:
  train_data_path: null
  test_data_path: null
  prompts_per_rollout: null
  responses_per_prompt: null
  
actor:
  model_name: null
  tokenizer_name: ${actor.model_name}
  use_liger_kernel: false
  gradient_checkpointing: true
  ddp_size: 1
  tp_size: 1
  sp_size: 1
  max_length_per_device: null
  max_inference_length_per_device: ${actor.max_length_per_device}
  temperature: ${rollout.train_sampling_params.temperature}
  update_per_rollout: 1
  clip: 0.2
  agg_mode: all_token_mean
  lr: 1e-6
  weight_decay: 1e-2
  max_grad_norm: 1.0
  scheduler: constant
  warmup_ratio: 0.1
  freeze_steps: 0
  offload_model: false
  offload_optimizer: true

  kl:
    coef: 0.0
    type: null # `reward` or `loss`
    reward_estimator: k3  # GRPO-specific: k3 estimator
    loss_estimator: k2
    # `k1`, `k2` or `k3`. See http://joschu.net/blog/kl-approx.html.

  entropy:
    coef: 0.0

rollout:
  model_name: ${actor.model_name}
  tokenizer_name: ${rollout.model_name}
  tp_size: 1
  gpu_memory_utilization: 0.5
  responses_per_prompt: ${data.responses_per_prompt}
  apply_chat_template: true
  train_sampling_params:
    temperature: 1.0
    max_new_tokens: null
  test_sampling_params:
    temperature: 0.0
    max_new_tokens: ${rollout.train_sampling_params.max_new_tokens}
  max_turns: 1
  env_path: null
  dynamic_filtering: true

ref_actor:
  model_name: ${actor.model_name}
  tokenizer_name: ${ref_actor.model_name}
  use_liger_kernel: ${actor.use_liger_kernel}
  ddp_size: ${actor.ddp_size}
  tp_size: ${actor.tp_size}
  sp_size: ${actor.sp_size}
  max_inference_length_per_device: ${actor.max_length_per_device}
  temperature: ${rollout.train_sampling_params.temperature}
  offload_model: ${actor.offload_model}

critic:
  model_name: ${actor.model_name}
  tokenizer_name: ${critic.model_name}
  gradient_checkpointing: ${actor.gradient_checkpointing}
  ddp_size: ${actor.ddp_size}
  tp_size: ${actor.tp_size}
  sp_size: ${actor.sp_size}
  max_length_per_device: ${actor.max_length_per_device}
  max_inference_length_per_device: ${critic.max_length_per_device}
  update_per_rollout: 12
  clip: 0.5
  agg_mode: ${actor.agg_mode}
  lr: 5e-6
  weight_decay: ${actor.weight_decay}
  max_grad_norm: ${actor.max_grad_norm}
  scheduler: ${actor.scheduler}
  warmup_ratio: ${actor.warmup_ratio}
  offload_model: ${actor.offload_model}
  offload_optimizer: ${actor.offload_optimizer}

adv:
  estimator: reinforce # GRPO default: `reinforce` (Dr. GRPO)
  gamma: 1.0
  lamda: 1.0
  global_norm: false
  norm_var: true  # GRPO-specific: normalize variance
  
trainer:
  project: null
  experiment_name: null
  load_ckpt_from: null
  n_epochs: 1
  test_freq: null
  save_dir: ckpts/${trainer.experiment_name}
  save_freq: null
  use_wandb: true
